FROM clickhouse/clickhouse-server:23.5.5.92

COPY local.xml /etc/clickhouse-server/config.d/local.xml

COPY macros1.xml /etc/clickhouse-server/config.d/macros.xml

COPY keeper1.xml /etc/clickhouse-server/config.d/keeper.xml
