FROM clickhouse/clickhouse-server:23.11.1.2711

COPY local.xml /etc/clickhouse-server/config.d/local.xml

COPY macros1.xml /etc/clickhouse-server/config.d/macros.xml

COPY keeper1.xml /etc/clickhouse-server/config.d/keeper.xml
