FROM clickhouse/clickhouse-server:23.1.3.5

COPY local.xml /etc/clickhouse-server/config.d/local.xml

COPY macros2.xml /etc/clickhouse-server/config.d/macros.xml

COPY keeper2.xml /etc/clickhouse-server/config.d/keeper.xml
